### ISSUE TITLE
Pagination not working as expected

### ISSUE THREAD

**Issue by comister** [sliverman69/aws_describe_snapshots#1]
Hi,

This script saved my life with the pagination the retrieval is much faster than doing the Standard describe-snapshots.
Nevertheless, I am facing a challenge with a slightly adapted version which was supposed to utilize the nextToken to pass the retrieval to a subsequent call of the same script.

I would require this to work through about 100.000 snapshots within a Lambda function (which is limited to max 5 minutes of runtime) ... so the approach is to do i.e. a maxResult of 1000 and a PageSize of 1000, grabbing the nextToken and invoking the same function again passing the nextToken along which will then be used in the PaginationConfig (in the documentation (http://boto3.readthedocs.io/en/latest/reference/services/ec2.html#EC2.Paginator.DescribeSnapshots) the property is called 'StartToken', using that it errored out blaming me that I use a unknown property, replacing it with 'nextToken' removed the blaming and it is running through.

Nevertheless, using that approach it seems each subsequent call works on the same snapshots even if I use the token ... maybe I use it wrong, I am not sure ... I am a bit fighting with this maxItems and PageSize, I am actually not 100% clear how its behaving, maybe I have to use maxResults = 100000 (in my special case) and page = 1000 ... afterwards not going through the for loop, just pull the first "page" and pass the token further after working through this 1000 entries (I have not tried this due to lack of really knowing whats going on)

Any hint appreciated !

**Comment by khrystoph** [comment]
Hey,

One thing I found out while working on this is that the SDK will automatically paginate and run through all the responses with one go. You can certainly adjust the  startToken and nextToken stuff (ie. when you get the next token, you would then set the new startToken to the value of the last token, but the SDK will do it automagically).

The part about maxResults and PageSize are just to vary your results per page and total results returned. If you have a maxResults = 0, I think it removes the limit from your API calls (if I remember right). However, you can always just bump the value to 100k or 150k (written in the script as 100000 or 150000) or any number above that.

pageSize determines how many results are returned in a single paginated call. The SDK supports up to 1000. If you are Calling ALL snapshots (not just the ones in your account) the number returned (as you can see by running the script), will be lower than 1000. I'm not sure WHY that is, but it seems to be something on the back end that is limiting the request. If you specify your account as the Owner (as is done in the script), you can get more results per request.

Also, the API will implement retry logic automatically as well (again, if I remember correctly).

So, really, all you need to adjust in the script is the number of results in maxResult to include your whole dataset.
